/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class crearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form crearCuenta
     */
    public crearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        monto = new javax.swing.JTextField();
        BTNcrear = new javax.swing.JButton();
        tiposCuentas = new javax.swing.JComboBox<>();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Cuenta");
        setMinimumSize(new java.awt.Dimension(1066, 625));
        getContentPane().setLayout(null);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1027, 10, 40, 30);

        inicio.setBorderPainted(false);
        getContentPane().add(inicio);
        inicio.setBounds(820, 20, 180, 20);

        monto.setBackground(new java.awt.Color(248, 249, 253));
        monto.setBorder(null);
        getContentPane().add(monto);
        monto.setBounds(450, 480, 270, 30);

        BTNcrear.setBorderPainted(false);
        getContentPane().add(BTNcrear);
        BTNcrear.setBounds(910, 460, 120, 120);

        tiposCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(tiposCuentas);
        tiposCuentas.setBounds(446, 380, 180, 27);

        name.setFont(new java.awt.Font("Raleway", 1, 25)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Jean Dean");
        getContentPane().add(name);
        name.setBounds(160, 90, 400, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/crearCuenta.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1070, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNcrear;
    public javax.swing.JButton close;
    public javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField monto;
    public javax.swing.JLabel name;
    public javax.swing.JComboBox<String> tiposCuentas;
    // End of variables declaration//GEN-END:variables
}
