/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class cuenta extends javax.swing.JFrame {

    /**
     * Creates new form cuenta
     */
    public cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        balanceCuenta = new javax.swing.JLabel();
        balanceCuenta2 = new javax.swing.JLabel();
        terminacionCuenta = new javax.swing.JLabel();
        ultimoMov = new javax.swing.JLabel();
        transferencia = new javax.swing.JButton();
        movimientos = new javax.swing.JButton();
        crearCuenta = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        deposito = new javax.swing.JLabel();
        retiro = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 1066, 625));
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Raleway", 1, 25)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Jean Dean");
        getContentPane().add(name);
        name.setBounds(160, 90, 370, 40);

        balanceCuenta.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        balanceCuenta.setForeground(new java.awt.Color(255, 255, 255));
        balanceCuenta.setText("5,123");
        getContentPane().add(balanceCuenta);
        balanceCuenta.setBounds(850, 80, 190, 40);

        balanceCuenta2.setFont(new java.awt.Font("Roboto", 3, 25)); // NOI18N
        balanceCuenta2.setForeground(new java.awt.Color(255, 255, 255));
        balanceCuenta2.setText("5,123");
        getContentPane().add(balanceCuenta2);
        balanceCuenta2.setBounds(110, 300, 150, 30);

        terminacionCuenta.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        terminacionCuenta.setText("2 9 0 9");
        getContentPane().add(terminacionCuenta);
        terminacionCuenta.setBounds(930, 240, 100, 30);

        ultimoMov.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        ultimoMov.setText("28/28/2019");
        getContentPane().add(ultimoMov);
        ultimoMov.setBounds(690, 310, 170, 30);

        transferencia.setBorderPainted(false);
        getContentPane().add(transferencia);
        transferencia.setBounds(20, 430, 90, 90);

        movimientos.setBorderPainted(false);
        getContentPane().add(movimientos);
        movimientos.setBounds(330, 430, 90, 90);

        crearCuenta.setBorderPainted(false);
        getContentPane().add(crearCuenta);
        crearCuenta.setBounds(170, 430, 90, 90);

        fecha.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        fecha.setText("28/08/2019");
        getContentPane().add(fecha);
        fecha.setBounds(440, 470, 130, 30);

        deposito.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        deposito.setText("$100");
        getContentPane().add(deposito);
        deposito.setBounds(710, 470, 90, 30);

        retiro.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        retiro.setText("$500");
        getContentPane().add(retiro);
        retiro.setBounds(940, 470, 90, 30);

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/goldCard.png"))); // NOI18N
        card.setBounds(new java.awt.Rectangle(78, 184, 290, 160));
        getContentPane().add(card);
        card.setBounds(80, 180, 290, 160);

        volver.setBorderPainted(false);
        getContentPane().add(volver);
        volver.setBounds(810, 0, 190, 40);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1027, 9, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/cuenta.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1070, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balanceCuenta;
    public javax.swing.JLabel balanceCuenta2;
    public javax.swing.JLabel card;
    public javax.swing.JButton close;
    public javax.swing.JButton crearCuenta;
    public javax.swing.JLabel deposito;
    public javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton movimientos;
    public javax.swing.JLabel name;
    public javax.swing.JLabel retiro;
    public javax.swing.JLabel terminacionCuenta;
    public javax.swing.JButton transferencia;
    public javax.swing.JLabel ultimoMov;
    public javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
