/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        BTNcrearCuenta = new javax.swing.JButton();
        BTNmovimientos = new javax.swing.JButton();
        BTNtransferencia = new javax.swing.JButton();
        basicMoney = new javax.swing.JLabel();
        basicCard = new javax.swing.JLabel();
        goldMoney = new javax.swing.JLabel();
        goldCard = new javax.swing.JLabel();
        premiumMoney = new javax.swing.JLabel();
        premiumCard = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBounds(new java.awt.Rectangle(0, 0, 1066, 625));
        setMinimumSize(new java.awt.Dimension(1066, 625));
        getContentPane().setLayout(null);

        balance.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("5,329");
        balance.setToolTipText("");
        getContentPane().add(balance);
        balance.setBounds(780, 90, 150, 30);

        name.setFont(new java.awt.Font("Raleway", 1, 25)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Jane Dean");
        getContentPane().add(name);
        name.setBounds(170, 100, 350, 30);

        BTNcrearCuenta.setBorderPainted(false);
        getContentPane().add(BTNcrearCuenta);
        BTNcrearCuenta.setBounds(500, 460, 110, 110);

        BTNmovimientos.setBorderPainted(false);
        getContentPane().add(BTNmovimientos);
        BTNmovimientos.setBounds(840, 460, 110, 110);

        BTNtransferencia.setBorderPainted(false);
        getContentPane().add(BTNtransferencia);
        BTNtransferencia.setBounds(170, 460, 110, 110);

        basicMoney.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        basicMoney.setForeground(new java.awt.Color(255, 255, 255));
        basicMoney.setText("111,111");
        getContentPane().add(basicMoney);
        basicMoney.setBounds(120, 300, 170, 20);

        basicCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/basicCard.png"))); // NOI18N
        getContentPane().add(basicCard);
        basicCard.setBounds(80, 180, 290, 160);

        goldMoney.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        goldMoney.setForeground(new java.awt.Color(255, 255, 255));
        goldMoney.setText("No disponible");
        goldMoney.setBounds(new java.awt.Rectangle(460, 304, 170, 20));
        getContentPane().add(goldMoney);
        goldMoney.setBounds(460, 300, 170, 20);

        goldCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/goldCard.png"))); // NOI18N
        goldCard.setBounds(new java.awt.Rectangle(417, 185, 290, 160));
        getContentPane().add(goldCard);
        goldCard.setBounds(410, 180, 290, 160);

        premiumMoney.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        premiumMoney.setForeground(new java.awt.Color(255, 255, 255));
        premiumMoney.setText("No disponible");
        getContentPane().add(premiumMoney);
        premiumMoney.setBounds(790, 310, 170, 20);

        premiumCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/premiumCard.png"))); // NOI18N
        premiumCard.setBounds(new java.awt.Rectangle(754, 188, 290, 160));
        getContentPane().add(premiumCard);
        premiumCard.setBounds(750, 190, 290, 160);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1030, 10, 30, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/principal.png"))); // NOI18N
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 1066, 625));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1066, 625);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNcrearCuenta;
    public javax.swing.JButton BTNmovimientos;
    public javax.swing.JButton BTNtransferencia;
    public javax.swing.JLabel balance;
    public javax.swing.JLabel basicCard;
    public javax.swing.JLabel basicMoney;
    public javax.swing.JButton close;
    public javax.swing.JLabel goldCard;
    public javax.swing.JLabel goldMoney;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel name;
    public javax.swing.JLabel premiumCard;
    public javax.swing.JLabel premiumMoney;
    // End of variables declaration//GEN-END:variables
}
