/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class movimientos extends javax.swing.JFrame {

    /**
     * Creates new form movimientos
     */
    public movimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        terminacionCuenta = new javax.swing.JLabel();
        balance2 = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        crearCuenta = new javax.swing.JButton();
        BTNtransferencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numCuenta = new javax.swing.JComboBox<>();
        ultimoMov = new javax.swing.JLabel();
        consulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movimientos");
        setMinimumSize(new java.awt.Dimension(1066, 625));
        getContentPane().setLayout(null);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1030, 10, 30, 29);

        inicio.setBorderPainted(false);
        getContentPane().add(inicio);
        inicio.setBounds(820, 10, 170, 29);

        balance.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("5,123");
        getContentPane().add(balance);
        balance.setBounds(850, 80, 190, 40);

        name.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Jean Dean");
        getContentPane().add(name);
        name.setBounds(170, 100, 340, 31);

        terminacionCuenta.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        terminacionCuenta.setText("2 9 0 9");
        getContentPane().add(terminacionCuenta);
        terminacionCuenta.setBounds(930, 240, 110, 30);

        balance2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        balance2.setForeground(new java.awt.Color(255, 255, 255));
        balance2.setText("5,1234");
        getContentPane().add(balance2);
        balance2.setBounds(120, 300, 150, 30);

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/newCard.png"))); // NOI18N
        getContentPane().add(card);
        card.setBounds(80, 190, 290, 150);
        getContentPane().add(fechaInicio);
        fechaInicio.setBounds(50, 390, 160, 26);
        getContentPane().add(fechaFin);
        fechaFin.setBounds(270, 390, 150, 26);

        crearCuenta.setBorderPainted(false);
        getContentPane().add(crearCuenta);
        crearCuenta.setBounds(250, 500, 97, 100);

        BTNtransferencia.setBorderPainted(false);
        BTNtransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(BTNtransferencia);
        BTNtransferencia.setBounds(90, 500, 100, 100);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("Seleccionar cuenta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 430, 150, 17);

        numCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(numCuenta);
        numCuenta.setBounds(50, 460, 170, 27);

        ultimoMov.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        getContentPane().add(ultimoMov);
        ultimoMov.setBounds(680, 280, 290, 40);

        consulta.setText("Consultar");
        getContentPane().add(consulta);
        consulta.setBounds(267, 460, 130, 29);

        jScrollPane2.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(440, 350, 490, 240);

        jScrollPane1.setBorder(null);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(1);
        jTextArea2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(930, 350, 120, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/movimientos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1066, 625);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNtransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNtransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNtransferencia;
    public javax.swing.JLabel balance;
    public javax.swing.JLabel balance2;
    public javax.swing.JLabel card;
    public javax.swing.JButton close;
    public javax.swing.JButton consulta;
    public javax.swing.JButton crearCuenta;
    public com.toedter.calendar.JDateChooser fechaFin;
    public com.toedter.calendar.JDateChooser fechaInicio;
    public javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JLabel name;
    public javax.swing.JComboBox<String> numCuenta;
    public javax.swing.JLabel terminacionCuenta;
    public javax.swing.JLabel ultimoMov;
    // End of variables declaration//GEN-END:variables
}
