/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class movimientos extends javax.swing.JFrame {

    /**
     * Creates new form movimientos
     */
    public movimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        terminacionTarjeta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        crearCuenta = new javax.swing.JButton();
        BTNtransferencia = new javax.swing.JButton();
        fechaMov = new javax.swing.JLabel();
        deposito = new javax.swing.JLabel();
        retiro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movimientos");
        setMinimumSize(new java.awt.Dimension(1066, 625));
        getContentPane().setLayout(null);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1030, 10, 30, 29);

        inicio.setBorderPainted(false);
        getContentPane().add(inicio);
        inicio.setBounds(820, 10, 170, 29);

        balance.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("5,123");
        getContentPane().add(balance);
        balance.setBounds(850, 80, 190, 40);

        name.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Jean Dean");
        getContentPane().add(name);
        name.setBounds(170, 100, 340, 31);

        terminacionTarjeta.setFont(new java.awt.Font("Roboto", 0, 25)); // NOI18N
        terminacionTarjeta.setText("2 9 0 9");
        getContentPane().add(terminacionTarjeta);
        terminacionTarjeta.setBounds(930, 240, 110, 30);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("5,1234");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 300, 150, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/goldCard.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 190, 290, 150);
        getContentPane().add(fechaInicio);
        fechaInicio.setBounds(50, 390, 160, 26);
        getContentPane().add(fechaFin);
        fechaFin.setBounds(280, 390, 140, 26);

        crearCuenta.setBorderPainted(false);
        getContentPane().add(crearCuenta);
        crearCuenta.setBounds(250, 500, 97, 100);

        BTNtransferencia.setBorderPainted(false);
        getContentPane().add(BTNtransferencia);
        BTNtransferencia.setBounds(90, 500, 100, 100);

        fechaMov.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        fechaMov.setText("28/08/2019 | 06:45:34");
        getContentPane().add(fechaMov);
        fechaMov.setBounds(440, 390, 220, 20);

        deposito.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        deposito.setText("$1,000");
        getContentPane().add(deposito);
        deposito.setBounds(710, 380, 130, 30);

        retiro.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        retiro.setText("$500");
        getContentPane().add(retiro);
        retiro.setBounds(930, 380, 100, 24);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("Seleccionar cuenta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 430, 150, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 460, 170, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/movimientos.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1066, 625);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNtransferencia;
    public javax.swing.JLabel balance;
    public javax.swing.JButton close;
    public javax.swing.JButton crearCuenta;
    public javax.swing.JLabel deposito;
    public com.toedter.calendar.JDateChooser fechaFin;
    public com.toedter.calendar.JDateChooser fechaInicio;
    public javax.swing.JLabel fechaMov;
    public javax.swing.JButton inicio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel name;
    public javax.swing.JLabel retiro;
    public javax.swing.JLabel terminacionTarjeta;
    // End of variables declaration//GEN-END:variables
}
