/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luisangel
 */
public class transferencia extends javax.swing.JFrame {

    /**
     * Creates new form transferencia
     */
    public transferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        balanceCuenta = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        ultimoMov = new javax.swing.JLabel();
        cuentaDeposito = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        numCuenta = new javax.swing.JComboBox<>();
        BTNtransferir = new javax.swing.JButton();
        movimientos = new javax.swing.JButton();
        crearCuenta = new javax.swing.JButton();
        balanceCuenta2 = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        terminacionCuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencias");
        setMinimumSize(new java.awt.Dimension(1066, 625));
        getContentPane().setLayout(null);

        close.setBorderPainted(false);
        getContentPane().add(close);
        close.setBounds(1020, -1, 40, 40);

        inicio.setBorderPainted(false);
        getContentPane().add(inicio);
        inicio.setBounds(820, 10, 170, 30);

        balanceCuenta.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        balanceCuenta.setForeground(new java.awt.Color(255, 255, 255));
        balanceCuenta.setText("0");
        getContentPane().add(balanceCuenta);
        balanceCuenta.setBounds(840, 80, 210, 40);

        nombre.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Jean Dean");
        getContentPane().add(nombre);
        nombre.setBounds(170, 90, 290, 40);

        ultimoMov.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        ultimoMov.setText("28/08/1999");
        getContentPane().add(ultimoMov);
        ultimoMov.setBounds(680, 300, 280, 50);

        cuentaDeposito.setBackground(new java.awt.Color(248, 249, 253));
        cuentaDeposito.setBorder(null);
        getContentPane().add(cuentaDeposito);
        cuentaDeposito.setBounds(450, 446, 340, 30);

        monto.setBackground(new java.awt.Color(248, 249, 253));
        monto.setBorder(null);
        getContentPane().add(monto);
        monto.setBounds(450, 540, 340, 30);

        numCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(numCuenta);
        numCuenta.setBounds(76, 410, 210, 27);

        BTNtransferir.setBorderPainted(false);
        getContentPane().add(BTNtransferir);
        BTNtransferir.setBounds(910, 470, 97, 90);

        movimientos.setBorderPainted(false);
        getContentPane().add(movimientos);
        movimientos.setBounds(255, 499, 90, 100);

        crearCuenta.setBorderPainted(false);
        getContentPane().add(crearCuenta);
        crearCuenta.setBounds(90, 499, 100, 100);

        balanceCuenta2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        balanceCuenta2.setForeground(new java.awt.Color(255, 255, 255));
        balanceCuenta2.setText("0");
        getContentPane().add(balanceCuenta2);
        balanceCuenta2.setBounds(120, 300, 160, 24);

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/newCard.png"))); // NOI18N
        card.setAlignmentY(0.0F);
        card.setBounds(new java.awt.Rectangle(80, 178, 286, 170));
        getContentPane().add(card);
        card.setBounds(80, 180, 286, 170);

        terminacionCuenta.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        getContentPane().add(terminacionCuenta);
        terminacionCuenta.setBounds(930, 220, 90, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/IMG/transferencia.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1070, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNtransferir;
    public javax.swing.JLabel balanceCuenta;
    public javax.swing.JLabel balanceCuenta2;
    public javax.swing.JLabel card;
    public javax.swing.JButton close;
    public javax.swing.JButton crearCuenta;
    public javax.swing.JTextField cuentaDeposito;
    public javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField monto;
    public javax.swing.JButton movimientos;
    public javax.swing.JLabel nombre;
    public javax.swing.JComboBox<String> numCuenta;
    public javax.swing.JLabel terminacionCuenta;
    public javax.swing.JLabel ultimoMov;
    // End of variables declaration//GEN-END:variables
}
